#!/bin/bash 
/usr/bin/unsafe-operation-mode
mv /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf.save
mv /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf.save
/usr/bin/safe-operation-mode
