#!/bin/bash 

if [ -w "/" ] ; then 
    mv /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf.save /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf
    mv /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf.save /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf
else 
    /usr/bin/unsafe-operation-mode
    mv /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf.save /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf
    mv /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf.save /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf
    /usr/bin/safe-operation-mode
fi


