#!/bin/bash

# Stop platform services
systemctl stop $(systemctl show -p Wants waggle-platform.target | cut -d '=' -f 2)
if [ $? -ne 0 ]; then
    echo "Failed to stop waggle-platform services"
    exit 1
fi

# Unlock filesystem
waggle-fs-unlock
if [ $? -ne 0 ]; then
    echo "Could not unlock the system"
    exit 1
fi

# Force recovery
touch /root/do_recovery

# Recover the other media
systemctl isolate waggle-core.target
# Check when waggle-init.service starts
echo "Wait waggle-init.service to start..."
while [ -f /tmp/init_finished ]; do
    sleep 1
done

echo "wait waggle-init.service to end..."
while [ ! -f /tmp/init_finished ]; do
    sleep 1
done

# Switch back to operation mode
waggle-switch-to-operation-mode
