#!/bin/bash

echo "Switching to operation mode..."

current_device=$(mount | grep "on / " | cut -f 1 -d ' ' | grep -o "mmcblk[0-1]")
number_of_partitions=$(ls /sys/block/$current_device/ | grep $current_device | wc -l)
if [ "$number_of_partitions" != "3" ]; then
    echo "Must have 3 partitions"
    exit 1
fi

password=$(readlink /etc/shadow | grep aot | wc -l)
if [ "$password" != "1" ]; then
    echo -e "Password unlocked. Locking..."
    if [ -w / ]; then
        waggle-fs-unlock
    fi
    waggle-pw-lock
    if [ $? -ne 0 ]; then
        echo "Lock password failed, PLEASE LOCK THE PASSWORD MANUALLY"
        exit 1
    fi
fi

if [ -w / ]; then
    waggle-fs-lock
    if [ $? -ne 0 ]; then
        echo "Lock filesystem failed, PLEASE LOCK THE SYSTEM MANUALLY"
        exit 1
    fi
fi

echo "wellness" > /etc/waggle/hbmode
systemctl restart waggle-heartbeat.service
systemctl set-default waggle-platform.target
systemctl isolate waggle-platform.target

echo "Done"