#!/bin/bash

echo "Switching to operation mode..."

set -e

current_device=$(mount | grep "on / " | cut -f 1 -d ' ' | grep -o "mmcblk[0-1]")
number_of_partitions=$(ls /sys/block/$current_device/ | grep -o "${current_device}p[0-3]" | wc -l)
if [ "$number_of_partitions" != "3" ]; then
    echo "Must have 3 partitions. Switching failed"
    exit 1
fi

if [ ! -w / ]; then
    waggle-fs-unlock
fi

echo "wellness" > /etc/waggle/hbmode
systemctl restart waggle-heartbeat.service

waggle-pw-lock
password=$(readlink /etc/shadow | grep aot | wc -l)
if [ "$password" != "1" ]; then
    echo "Password lock failed. Switching failed"
    exit 1
fi

systemctl set-default waggle-platform.target
waggle-fs-lock
if [ $? -ne 0 ]; then
    echo "Locking filesystem failed, Switching failed"
    systemctl set-default waggle-core.target
    exit 1
fi
systemctl isolate waggle-platform.target

echo "Switching to operation mode...Done"
