#!/bin/bash

# determine Odroid model 
# - sets ${ODROID_MODEL} to either 'C' or 'XU3'
. /usr/lib/waggle/core/scripts/detect_odroid_model.sh

# Determine root and alternate boot medium root device paths
. /usr/lib/waggle/core/scripts/detect_disk_devices.sh

run_gn_tests() {
  ssh -i /usr/lib/waggle/SSL/guest/id_rsa_waggle_aot_guest_node waggle@10.31.81.10 touch start_test
  ssh -i /usr/lib/waggle/SSL/guest/id_rsa_waggle_aot_guest_node waggle@10.31.81.10 systemctl start waggle-test-node
}

run_tests() {
  if [ "${ODROID_MODEL}" == "C" ]; then
    if [ "${CURRENT_DISK_DEVICE_TYPE}" == "SD" ]; then
      run_gn_tests
    fi
    local script_dir="/usr/lib/waggle/nodecontroller/scripts/"
  elif [ "${ODROID_MODEL}" == "XU3" ]; then
    local script_dir="/usr/lib/waggle/guestnode/scripts/"
  else
    echo "ERROR: Odroid model not detected."
    exit 1
  fi
  ${script_dir}test_node.sh > /home/waggle/test_node_${ODROID_MODEL}_${CURRENT_DISK_DEVICE_TYPE}.log
}

generate_report() {
  # Retrieve the eMMC test log
  cp /media/test/home/waggle/test_node_${ODROID_MODEL}_${OTHER_DISK_DEVICE_TYPE}.log /home/waggle/

  if [ "${ODROID_MODEL}" == "C" ]; then
    local report_file="/home/waggle/test-report.txt"
    echo "Node Controller SD Test Results" >> $report_file
    echo "-------------------------------" >> $report_file
    cat /home/waggle/test_node_C_SD.log >> $report_file

    echo >> $report_file
    echo "Node Controller eMMC Test Results" >> $report_file
    echo "---------------------------------" >> $report_file
    cat /home/waggle/test_node_C_MMC.log >> $report_file

    # wait a reasonable amount of time for the GN to finish its tests
    local tries=0
    local max_tries=6
    local gn_done=0
    while [ $tries -lt $max_tries ]; do
      if [[ ! -e /home/waggle/test_node_XU3_SD.log || ! -e /home/waggle/test_node_XU3_MMC.log ]]; then
        tries=$(expr $tries + 1)
        echo "Waiting for GN test logs..."
        sleep 10
      else
        gn_done=1
        tries=$max_tries
      fi
    done

    if [ $gn_done -eq 1 ]; then
      echo >> $report_file
      echo "Guest Node SD Test Results" >> $report_file
      echo "--------------------------" >> $report_file
      cat /home/waggle/test_node_XU3_SD.log >> $report_file

      echo >> $report_file
      echo "Guest Node eMMC Test Results" >> $report_file
      echo "----------------------------" >> $report_file
      cat /home/waggle/test_node_XU3_MMC.log >> $report_file
    else
      echo >> $report_file
      echo "########################" >> $report_file
      echo "Guest Node Tests Failed!" >> $report_file
      echo "########################" >> $report_file
    fi
  elif [ "${ODROID_MODEL}" == "XU3" ]; then
    scp /home/waggle/test_node_*.log -i /usr/lib/waggle/SSL/guest/id_rsa_waggle_aot_guest_node waggle@10.31.81.10:
  else
    echo "ERROR: Odroid model not detected."
    exit 2
  fi
}

mount | grep '/media/test' && true
if [ $? -eq 1 ]; then
  mount "${OTHER_DISK_DEVICE}p2" /media/test
fi

start_file=/home/waggle/start_test
continue_file=/home/waggle/continue_test
finish_file=/home/waggle/finish_test
if [ -e ${start_file} ] ; then
  run_tests
  rm ${start_file}
  if [ "${CURRENT_DISK_DEVICE_TYPE}" == "SD" ]; then
    touch /media/test${continue_file}
    wagman-client bs 0 emmc
  else
    touch /media/test${finish_file}
    wagman-client bs 0 sd
  fi
  #wagman-client stop 0 0
elif [ -e ${continue_file} ]; then
  run_tests
  rm ${continue_file}
  touch /media/test${finish_file}
  wagman-client bs 0 sd
  #wagman-client stop 0 0
elif [ -e ${finish_file} ]; then
  generate_report
  rm ${finish_file}
fi
