#!/bin/bash

if [ $(readlink -f /etc/shadow) == '/etc/passwds/shadow_aot' ]; then 
  passwordmode="L"
elif [ $(readlink -f /etc/shadow) == '/etc/passwds/shadow_waggle' ]; then 
  passwordmode="U"
else 
  passwordmode="X"
fi

if [ -f "/etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf" ] || [ -f "/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf" ]; then 
  consolemode="U"
elif [ -f "/etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf.save" ] && [ -f "/etc/systemd/system/serial-getty@ttyS0.service.d/override.conf.save" ]; then 
  consolemode="L"
else 
  consolemode="X"
fi

if [ -w "/" ] ; then 
   filesysmode="U"
else 
   filesysmode="L"
fi


