#!/bin/bash -e

mode="$1"

matches() {
    echo $mode | grep -q $1
}

if ! matches '^[LU][LU][LU][CP]$'; then
    echo 'invalid mode. mode must match [LU][LU][LU][CP].'
    exit 1
fi

if matches $(waggle_get_mode); then
    echo 'already in correct mode. no actions will be taken.'
    exit 0
fi

if matches 'LU..'; then
    echo 'warning! console should be locked if password locked.'
    # exit 1
fi

# almost all actions currently require writable fs
waggle-fs-unlock

if matches 'L...'; then
    echo lock pw
    waggle-pw-lock
else
    echo unlock pw
    waggle-pw-unlock
fi

if matches '.L..'; then
    echo lock console
    waggle-console-lock
else
    echo unlock console
    waggle-console-unlock
fi

if matches '...C'; then
    echo core mode
    systemctl set-default waggle-core.target
    systemctl isolate waggle-core.target
else
    echo platform mode
    systemctl set-default waggle-platform.target
    systemctl isolate waggle-platform.target
fi

if matches '..L.'; then
    waggle-fs-lock
fi
