#!/bin/bash

echo "Locking consoles"

for d in /etc/systemd/system/serial-getty@*.service.d/; do
    echo "Locking console $d"
    (cd $d; mv override.conf override.conf.save)
done

echo "Done locking consoles"
