#!/bin/bash -e

waggle-mode-burnin-core

# Force recovery
mkdir -p /wagglerw
touch /wagglerw/do_recovery
systemctl restart waggle-init.service

echo "Waiting for recovery to start"
while [ -f /wagglerw/init_finished ]; do
    echo -n '.'
    sleep 2
done

echo "Waiting for recovery to end."

while [ ! -f /wagglerw/init_finished ]; do
    echo -n '.'
    sleep 10
done

waggle-mode-burnin
