#!/bin/bash
# ANL:waggle-license
#  This file is part of the Waggle Platform.  Please see the file
#  LICENSE.waggle.txt for the legal details of the copyright and software
#  license.  For more details on the Waggle project, visit:
#           http://www.wa8.gl
# ANL:waggle-license

echo "cleaning up journal logs"
journalctl --vacuum-size=100M

echo "cleaning up old rabbitmq logs"
rm /var/log/rabbitmq/*.log.*

echo "attempting to rotate rabbitmq log"
if ! rabbitmqctl rotate_logs; then
    systemctl restart rabbitmq-server
    rabbitmqctl rotate_logs
fi

echo "cleaning up newly rotated rabbitmq logs"
rm /var/log/rabbitmq/*.log.*
