#!/bin/bash

echo "Unlocking consoles"

for d in /etc/systemd/system/serial-getty@*.service.d/; do
    echo "Unlocking console $d"
    (cd $d; mv override.conf.save override.conf)
done

echo "Done unlocking consoles"
