#!/bin/bash
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

if udevadm info --q property -a /dev/disk/by-label/rootfs | grep -q 'ATTRS{type}.*SD'; then
    echo sd
    exit 0
fi

if udevadm info --q property -a /dev/disk/by-label/rootfs | grep -q 'ATTRS{type}.*MMC'; then
    echo emmc
    exit 0
fi

>&2 echo unknown media
exit 1
