#!/bin/bash
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

echo "Unlocking consoles"

for d in /etc/systemd/system/serial-getty@*.service.d/; do
    echo "Unlocking console $d"
    (cd $d; mv override.conf.save override.conf)
done

echo "Done unlocking consoles"
