#!/bin/bash
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

rm -rf /tmp/audit
mkdir -p /tmp/audit
cd /tmp/audit

pip freeze > pip
pip3 freeze > pip3
dpkg -l > dpkg

shasum *
