#!/bin/bash -e
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

waggle-mode-burnin-core

# Force recovery
mkdir -p /wagglerw
touch /wagglerw/do_recovery
systemctl restart waggle-init.service

echo "Waiting for recovery to start"
while [ -f /wagglerw/init_finished ]; do
    echo -n '.'
    sleep 2
done

echo "Waiting for recovery to end."

while [ ! -f /wagglerw/init_finished ]; do
    echo -n '.'
    sleep 10
done

waggle-mode-burnin
