#!/bin/bash

mv /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf /etc/systemd/system/serial-getty@ttySAC2.service.d/override.conf.save || true
mv /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf.save || true
