#!/bin/bash
# ANL:waggle-license
# This file is part of the Waggle Platform.  Please see the file
# LICENSE.waggle.txt for the legal details of the copyright and software
# license.  For more details on the Waggle project, visit:
#          http://www.wa8.gl
# ANL:waggle-license

fatal() {
    >&2 echo $*
    exit 1
}

# Stop platform services
if ! systemctl stop -- $(systemctl show -p Wants waggle-platform.target | cut -d '=' -f 2); then
    fatal "Failed to stop waggle-platform services. Unlocking failed"
fi

# Remount as RW
if ! mount -o remount,rw /; then
    fatal "error: remount rootfs failed"
fi

if [ ! -w / ] ; then
    fatal "error: rootfs is not writable"
fi

# checking if the /etc/fstab_ro file exists, and provide backward compatability for old systems.
if [ ! -f /etc/fstab_ro ]; then
    # old system, so making changes in fstab
    content=`cat /etc/fstab | grep ' \/ ' | sed 's/ro,/rw,/'`
    sed -i '/ \/ /d' /etc/fstab
    sed -i "1i ${content}" /etc/fstab

    if [ $(cat /etc/fstab | grep ' \/ ' | grep 'rw,' | wc -l) -eq 0 ] ; then
        fatal "waggle-fs-unlock failed"
    fi
else
   # new system, so just moving files appropriately
   # checking if the files are indeed correct
   if [ $(diff /etc/fstab_ro /etc/fstab_rw  | head -1) == '1c1' ]; then
        cp /etc/fstab_rw /tmp/fstab_rw_tmp
        mv /tmp/fstab_rw_tmp /etc/fstab
   else
       fatal "/etc/fstab_* files are inconsistent. Please check files."
   fi
fi

systemctl set-default waggle-core.target
rm -f /root/fs_locked

echo "waggle-fs-unlock is done"
