#!/bin/bash -e

mode="$1"

matches() {
    echo $mode | grep -q $1
}

matches_required() {
    echo $mode | cut -c -4 | grep -q $1
}

if ! matches '^[LU][LU][LU][CP][AWX]$'; then
    echo 'invalid mode. mode must match [LU][LU][LU][CP][AWX].'
    exit 1
fi

if matches_required $(waggle_get_mode); then
    echo 'already in correct mode. no actions will be taken.'
    exit 0
fi

failsafe() {
    if [ $? -eq 0 ]; then
        return
    fi

    echo 'an error occured. attempting to set system to safe mode.'
    set +e
    systemctl set-default waggle-core.target
    systemctl isolate waggle-core.target
    waggle-pw-lock
    waggle-console-lock
    waggle-fs-lock
}

trap failsafe EXIT

# almost all actions currently require writable fs
waggle-fs-unlock

if matches 'L....'; then
    echo lock pw
    waggle-pw-lock
else
    echo unlock pw
    waggle-pw-unlock
fi

if matches '.L...'; then
    echo lock console
    waggle-console-lock
else
    echo unlock console
    waggle-console-unlock
fi

if matches '....A'; then
    waggle-heartbeat-always-mode
elif matches '....W'; then
    waggle-heartbeat-wellness-mode
fi

if matches '...C.'; then
    echo core mode
    systemctl set-default waggle-core.target
    systemctl isolate waggle-core.target
else
    echo platform mode
    systemctl set-default waggle-platform.target
    systemctl isolate waggle-platform.target
fi

if matches '..L..'; then
    waggle-fs-lock
fi
