#!/bin/bash

mode="$1"

matches() {
    echo $mode | grep -q $1
}

if ! matches '^[LU][LU][LU][CP]$'; then
    echo 'invalid mode. mode must match [LU][LU][LU][CP].'
    exit 1
fi

if matches 'LU..'; then
    echo 'invalid mode. console must be locked if password locked.'
    exit 1
fi

if matches 'L...'; then
    echo lock pw
    waggle-pw-lock
else
    echo unlock pw
    waggle-pw-unlock
fi

if matches '.L..'; then
    echo lock console
    waggle-console-lock
else
    echo unlock console
    waggle-console-unlock
fi

if matches '..L.'; then
    echo lock fs
    waggle-fs-lock
else
    echo unlock fs
    waggle-fs-unlock
fi

if matches '...C'; then
    echo core mode
    systemctl set-default waggle-core.target
    systemctl isolate waggle-core.target
else
    echo platform mode
    systemctl set-default waggle-platform.target
    systemctl isolate waggle-platform.target
fi
