#!/bin/bash

# Stop platform services
systemctl stop -- $(systemctl show -p Wants waggle-platform.target | cut -d '=' -f 2)
if [ $? -ne 0 ]; then
    echo "Failed to stop waggle-platform services. Unlocking failed"
    exit 1
fi

mount -o remount,rw /
if [ $? -ne 0 ] ; then
  echo "Mounting / as rw failed"
  exit 1
fi

content=`cat /etc/fstab | grep ' \/ ' | sed 's/ro,/rw,/'`
#uuid=$(blkid -o export /dev/mmcblk0p2 | grep "^UUID" |  cut -f2 -d '=')
sed -i '/ \/ /d' /etc/fstab
sed -i "1i ${content}" /etc/fstab

if [ $(cat /etc/fstab | grep ' \/ ' | grep 'rw,' | wc -l) -eq 0 ] ; then
  echo "waggle-fs-unlock failed"
  exit 1
fi

systemctl set-default waggle-core.target
rm -f /root/fs_locked

echo "waggle-fs-unlock is done"