#!/bin/bash -e

# Switch back to unsafe-operation mode
waggle-mode-burnin-core

# Force recovery
mkdir -p /wagglerw
touch /wagglerw/do_recovery

# Recover the other media
systemctl isolate waggle-core.target
# Check when waggle-init.service starts

echo "Waiting for recovery to start"
while [ -f /etc/waggle/init_finished ]; do
    echo -n '.'
    sleep 2
done

echo "Waiting for recovery to end."

while [ ! -f /etc/waggle/init_finished ]; do
    echo -n '.'
    sleep 10
done

# Switch back to operation mode
waggle-mode-burnin
